// vocab.js
// Keep ONLY vocabulary here. Add new lessons by appending new objects.

window.VOCAB = [
  // ---------------- Lesson 1 ----------------
  { chapter: 1, ar: "مَنْ هٰذَا؟", en: "Who is this?" },
  { chapter: 1, ar: "طَبِيبٌ", en: "Doctor" },
  { chapter: 1, ar: "وَلَدٌ", en: "Boy" },
  { chapter: 1, ar: "طَالِبٌ", en: "Student" },
  { chapter: 1, ar: "رَجُلٌ", en: "Man" },
  { chapter: 1, ar: "تَاجِرٌ", en: "Merchant" },
  { chapter: 1, ar: "كَلْبٌ", en: "Dog" },
  { chapter: 1, ar: "قِطٌّ", en: "Cat" },
  { chapter: 1, ar: "حِمَارٌ", en: "Donkey" },
  { chapter: 1, ar: "حِصَانٌ", en: "Horse" },
  { chapter: 1, ar: "وَ", en: "And" },
  { chapter: 1, ar: "جَمَلٌ", en: "Camel" },
  { chapter: 1, ar: "دِيكٌ", en: "Rooster" },
  { chapter: 1, ar: "مُدَرِّسٌ", en: "Teacher" },
  { chapter: 1, ar: "مِنْدِيلٌ", en: "Handkerchief" },
  { chapter: 1, ar: "نَجْمٌ", en: "Star" },
  { chapter: 1, ar: "هٰذَا", en: "This (m)" },
  { chapter: 1, ar: "بَيْتٌ", en: "House" },
  { chapter: 1, ar: "مَسْجِدٌ", en: "Mosque" },
  { chapter: 1, ar: "بَابٌ", en: "Door" },
  { chapter: 1, ar: "كِتَابٌ", en: "Book" },
  { chapter: 1, ar: "قَلَمٌ", en: "Pen" },
  { chapter: 1, ar: "مِفْتَاحٌ", en: "Key" },
  { chapter: 1, ar: "مَكْتَبٌ", en: "Desk" },
  { chapter: 1, ar: "سَرِيرٌ", en: "Bed" },
  { chapter: 1, ar: "كُرْسِيٌّ", en: "Chair" },
  { chapter: 1, ar: "مَا هٰذَا؟", en: "What is this?" },
  { chapter: 1, ar: "أَهٰذَا؟", en: "Is this?" },
  { chapter: 1, ar: "نَعَمْ", en: "Yes" },
  { chapter: 1, ar: "قَمِيصٌ", en: "Shirt" },
  { chapter: 1, ar: "لَا", en: "No" },
  { chapter: 1, ar: "مَنْ", en: "Who" },

  // ---------------- Lesson 2 ----------------
  { chapter: 2, ar: "مَا؟", en: "What?" },
  { chapter: 2, ar: "حَجَرٌ", en: "Stone" },
  { chapter: 2, ar: "لَبَنٌ", en: "Milk" },
  { chapter: 2, ar: "ذَٰلِكَ", en: "That" },
  { chapter: 2, ar: "أَذَٰلِكَ؟", en: "Is that?" },
  { chapter: 2, ar: "إِمَامٌ", en: "Leader" },
  { chapter: 2, ar: "سُكَّرٌ", en: "Sugar" },
  { chapter: 2, ar: "مَا ذَٰلِكَ؟", en: "What is that?" },

  // ---------------- Lesson 3 ----------------
  { chapter: 3, ar: "ثَقِيلٌ", en: "Heavy" },
  { chapter: 3, ar: "قَمَرٌ", en: "Moon" },
  { chapter: 3, ar: "خَفِيفٌ", en: "Light" },
  { chapter: 3, ar: "نَظِيفٌ", en: "Clean" },
  { chapter: 3, ar: "فَقِيرٌ", en: "Poor" },
  { chapter: 3, ar: "حُلْوٌ", en: "Sweet" },
  { chapter: 3, ar: "مَرِيضٌ", en: "Sick" },
  { chapter: 3, ar: "دَفْتَرٌ", en: "Notebook" },
  { chapter: 3, ar: "دُكَّانٌ", en: "Shop" },
  { chapter: 3, ar: "غَنِيٌّ", en: "Rich" },
  { chapter: 3, ar: "أَبٌ", en: "Father" },
  { chapter: 3, ar: "وَرَقٌ", en: "Paper" },
  { chapter: 3, ar: "تُفَّاحٌ", en: "Apple" },
  { chapter: 3, ar: "لَذِيذٌ", en: "Delicious" },
  { chapter: 3, ar: "طَبِيبٌ", en: "Doctor" },
  { chapter: 3, ar: "طَوِيلٌ", en: "Tall" },
  { chapter: 3, ar: "قَصِيرٌ", en: "Short" },
  { chapter: 3, ar: "أَخٌ", en: "Brother" },
  { chapter: 3, ar: "رَسُولٌ", en: "Messenger" },
  { chapter: 3, ar: "ال", en: "The" },
  { chapter: 3, ar: "مَكْسُورٌ", en: "Broken" },
  { chapter: 3, ar: "مَفْتُوحٌ", en: "Open" },
  { chapter: 3, ar: "جَالِسٌ", en: "Sitting" },
  { chapter: 3, ar: "وَاقِفٌ", en: "Standing" },
  { chapter: 3, ar: "جَدِيدٌ", en: "New" },
  { chapter: 3, ar: "قَدِيمٌ", en: "Old" },
  { chapter: 3, ar: "مَاءٌ", en: "Water" },
  { chapter: 3, ar: "بَارِدٌ", en: "Cold" },
  { chapter: 3, ar: "قَرِيبٌ", en: "Near" },
  { chapter: 3, ar: "بَعِيدٌ", en: "Far" },
  { chapter: 3, ar: "حَارٌّ", en: "Hot" },
  { chapter: 3, ar: "صَغِيرٌ", en: "Small" },
  { chapter: 3, ar: "كَبِيرٌ", en: "Big" },
  { chapter: 3, ar: "وَسِخٌ", en: "Dirty" },
  { chapter: 3, ar: "جَمِيلٌ", en: "Beautiful" },
  { chapter: 3, ar: "خُبْزٌ", en: "Bread" },
  { chapter: 3, ar: "عَيْنٌ", en: "Eye" },
  { chapter: 3, ar: "وَجْهٌ", en: "Face" },
  { chapter: 3, ar: "صَدِيقٌ", en: "Friend" },
  { chapter: 3, ar: "قُرْآنٌ", en: "Quraan" },
  { chapter: 3, ar: "صَلَاةٌ", en: "Prayer" },
  { chapter: 3, ar: "كَعْبَةٌ", en: "Kabah" },
  { chapter: 3, ar: "رَأْسٌ", en: "Head" },
  { chapter: 3, ar: "إِصْبَعٌ", en: "Finger" },
  { chapter: 3, ar: "صَابُونٌ", en: "Soap" },
  { chapter: 3, ar: "ظُفْرٌ", en: "Nail" },
  { chapter: 3, ar: "فَجْرٌ", en: "Dawn" },
  { chapter: 3, ar: "ظُهْرٌ", en: "Midday" },
  { chapter: 3, ar: "عَصْرٌ", en: "Afternoon/time" },
  { chapter: 3, ar: "مَغْرِبٌ", en: "Sunset" },
  { chapter: 3, ar: "عِشَاءٌ", en: "Evening" },
  { chapter: 3, ar: "جَنَّةٌ", en: "Garden/paradise" },
  { chapter: 3, ar: "غَدَاءٌ", en: "Lunch/dinner" },
  { chapter: 3, ar: "فَمٌ", en: "Mouth" },
  { chapter: 3, ar: "هَوَاءٌ", en: "Air" },
  { chapter: 3, ar: "يَدٌ", en: "Hand" },
  { chapter: 3, ar: "ثَوْبٌ", en: "Garment" },
  { chapter: 3, ar: "ذَهَبٌ", en: "Gold" },
  { chapter: 3, ar: "زَهْرَةٌ", en: "A flower" },
  { chapter: 3, ar: "سَمَكٌ", en: "A fish" },
  { chapter: 3, ar: "شَمْسٌ", en: "A sun" },
  { chapter: 3, ar: "صَدْرٌ", en: "Chest" },
  { chapter: 3, ar: "ضَيْفٌ", en: "Guest" },
  { chapter: 3, ar: "ظَهْرٌ", en: "Back" },
  { chapter: 3, ar: "لَحْمٌ", en: "Meat" },

  // ---------------- Lesson 4 ----------------
  { chapter: 4, ar: "مِرْحَاضٌ", en: "Toilet" },
  { chapter: 4, ar: "سَمَاءٌ", en: "Sky" },
  { chapter: 4, ar: "خَالِدٌ", en: "Khaalid" },
  { chapter: 4, ar: "حَامِدٌ", en: "Haamid" },
  { chapter: 4, ar: "فَاطِمَةُ", en: "Fatimah" },
  { chapter: 4, ar: "مَرْيَمُ", en: "Maryam" },
  { chapter: 4, ar: "عَائِشَةُ", en: "Aa’isha" },
  { chapter: 4, ar: "خَدِيجَةُ", en: "Khadeejah" },
  { chapter: 4, ar: "صَفِيَّةُ", en: "Safiyyah" },
  { chapter: 4, ar: "عَمَّارٌ", en: "Ammaar" },
  { chapter: 4, ar: "سَعِيدٌ", en: "Sa’eed" },
  { chapter: 4, ar: "عَلِيٌّ", en: "Ali" },
  { chapter: 4, ar: "رُقَيَّةُ", en: "Ruqayyah" },
  { chapter: 4, ar: "مِنْ", en: "From" },
  { chapter: 4, ar: "إِلَى", en: "To" },
  { chapter: 4, ar: "أَنْتَ", en: "You (m)" },
  { chapter: 4, ar: "خَرَجَ", en: "He left" },
  { chapter: 4, ar: "ذَهَبَ", en: "He went" },
  { chapter: 4, ar: "مُدِيرٌ", en: "Headmaster" },
  { chapter: 4, ar: "فِي", en: "In" },
  { chapter: 4, ar: "عَلَى", en: "On" },
  { chapter: 4, ar: "أَيْنَ", en: "Where" },
  { chapter: 4, ar: "مُحَمَّدٌ", en: "Muhammad" },
  { chapter: 4, ar: "هُوَ", en: "He" },
  { chapter: 4, ar: "غُرْفَةٌ", en: "A room" },
  { chapter: 4, ar: "يَاسِرُ", en: "Yaasir" },
  { chapter: 4, ar: "حَمَّامٌ", en: "Bathroom" },
  { chapter: 4, ar: "آمِنَةُ", en: "Aaminah" },
  { chapter: 4, ar: "مَطْبَخٌ", en: "Kitchen" },
  { chapter: 4, ar: "هِيَ", en: "She" },
  { chapter: 4, ar: "سَاعَةٌ", en: "Watch" },
  { chapter: 4, ar: "مَدْرَسَةٌ", en: "School" },
  { chapter: 4, ar: "جَامِعَةٌ", en: "University" },
  { chapter: 4, ar: "زَيْنَبُ", en: "Zainab" },
  { chapter: 4, ar: "فَصْلٌ", en: "Classroom" },
  { chapter: 4, ar: "أَنَا", en: "I" },
  { chapter: 4, ar: "الْيَابَانُ", en: "Japan" },
  { chapter: 4, ar: "الصِّينُ", en: "China" },
  { chapter: 4, ar: "الْهِنْدُ", en: "India" },
  { chapter: 4, ar: "سُوقٌ", en: "Market" },
  { chapter: 4, ar: "الْفِلِبِّينُ", en: "Philippines" },

  // ---------------- Lesson 5 ----------------
  { chapter: 5, ar: "فَيْصَل", en: "Faisal" },
  { chapter: 5, ar: "مَسْعُود", en: "Masood" },
  { chapter: 5, ar: "وَزِير", en: "Minister" },
  { chapter: 5, ar: "أُسْتَاذ", en: "Teacher/Professor" },
  { chapter: 5, ar: "سَيَّارَة", en: "Car" },
  { chapter: 5, ar: "اِبْن", en: "Son" },
  { chapter: 5, ar: "اللّٰه", en: "Allah" },
  { chapter: 5, ar: "اِسْم", en: "Name" },
  { chapter: 5, ar: "الْعِرَاق", en: "Iraq" },
  { chapter: 5, ar: "مُنَوَّرَة", en: "Illuminated" },
  { chapter: 5, ar: "يَا", en: "O.." },
  { chapter: 5, ar: "هُنَاك", en: "There" },
  { chapter: 5, ar: "هُنَا", en: "Here" },
  { chapter: 5, ar: "حَقِيبَة", en: "Bag" },
  { chapter: 5, ar: "تَحْت", en: "Under/beneath" },
  { chapter: 5, ar: "بِنْت", en: "Girl/daughter" },
  { chapter: 5, ar: "عَمّ", en: "Paternal uncle" },
  { chapter: 5, ar: "مُغْلَق", en: "Closed" },
  { chapter: 5, ar: "خَال", en: "Maternal uncle" },
  { chapter: 5, ar: "شَارِع", en: "Street" },

  // ---------------- Lesson 6 ----------------
  { chapter: 6, ar: "أُذُن", en: "Ear" },
  { chapter: 6, ar: "أَنْف", en: "Nose" },
  { chapter: 6, ar: "مُسْلِم", en: "Muslim" },
  { chapter: 6, ar: "شَاي", en: "Tea" },
  { chapter: 6, ar: "سَرِيع", en: "Fast" },
  { chapter: 6, ar: "نَافِذَة", en: "Window" },
  { chapter: 6, ar: "قَهْوَة", en: "Coffee" },
  { chapter: 6, ar: "ثَلَّاجَة", en: "Fridge" },
  { chapter: 6, ar: "أُمّ", en: "Mother" },
  { chapter: 6, ar: "فَلَّاح", en: "Farmer" },
  { chapter: 6, ar: "رِجْل", en: "Leg/foot" },
  { chapter: 6, ar: "بَقَرَة", en: "Cow" },
  { chapter: 6, ar: "قَدْر", en: "Cooking pot" },
  { chapter: 6, ar: "مَشْرِق", en: "East" },
  { chapter: 6, ar: "مَغْرِب", en: "West" },
  { chapter: 6, ar: "هٰذِهِ", en: "This is (f)" },
  { chapter: 6, ar: "أُخْت", en: "Sister" },
  { chapter: 6, ar: "أَيْضًا", en: "Also" },
  { chapter: 6, ar: "لِمَنْ", en: "Whose" },
  { chapter: 6, ar: "مِكْوَاة", en: "Iron" },
  { chapter: 6, ar: "جَدِيدَة", en: "New" },
  { chapter: 6, ar: "دَرَّاجَة", en: "Bicycle" },
  { chapter: 6, ar: "طَبِيبَة", en: "Doctor" },
  { chapter: 6, ar: "أَنَس", en: "Anas" },
  { chapter: 6, ar: "جِدًّا", en: "Very" },
  { chapter: 6, ar: "جَمِيلَة", en: "Beautiful" },
  { chapter: 6, ar: "مِلْعَقَة", en: "Spoon" },
  { chapter: 6, ar: "عَيْن", en: "Eye" },
  { chapter: 6, ar: "الْحَمْدُ لِلّٰهِ", en: "Praise belongs to Allah" },

  // ---------------- Lesson 7 ----------------
  { chapter: 7, ar: "تِلْكَ", en: "That is" },
  { chapter: 7, ar: "مُمَرِّضَة", en: "Nurse" },
  { chapter: 7, ar: "طَوِيلَة", en: "Tall" },
  { chapter: 7, ar: "دَجَاجَة", en: "Chicken" },
  { chapter: 7, ar: "نَاقَة", en: "She camel" },
  { chapter: 7, ar: "حَدِيقَة", en: "Garden" },
  { chapter: 7, ar: "قَصِيرَة", en: "Short" },
  { chapter: 7, ar: "بَطَّة", en: "Duck" },
  { chapter: 7, ar: "بَيْضَة", en: "Egg" },
  { chapter: 7, ar: "مُؤَذِّن", en: "Caller to prayer" },
  { chapter: 7, ar: "مُدَرِّسَة", en: "Teacher" },

  // ---------------- Lesson 8 ----------------
  { chapter: 8, ar: "خَلْف", en: "Behind" },
  { chapter: 8, ar: "أَمَام", en: "In front of" },
  { chapter: 8, ar: "أَمْرِيكَا", en: "America" },
  { chapter: 8, ar: "سِكِّين", en: "Knife" },
  { chapter: 8, ar: "إِنْكِلْتَرَا", en: "England" },
  { chapter: 8, ar: "مُسْتَشْفَى", en: "Hospital" },
  { chapter: 8, ar: "سُوَيْسَرَا", en: "Switzerland" },
  { chapter: 8, ar: "أَلْمَانِيَا", en: "Germany" },
  { chapter: 8, ar: "فَرَنْسَا", en: "France" },
  { chapter: 8, ar: "الْآنَ", en: "Now/just now" },
  { chapter: 8, ar: "عَبْدُ اللّٰهِ", en: "Abdullah" },
  { chapter: 8, ar: "عِيسَى", en: "Eesa" },
  { chapter: 8, ar: "مُوسَى", en: "Musa" },
  { chapter: 8, ar: "سَبُّورَة", en: "White/black board" },
  { chapter: 8, ar: "مِحْرَاب", en: "Niche" },

  // ---------------- Lesson 9 ----------------
  { chapter: 9, ar: "مَشْهُور", en: "Famous" },
  { chapter: 9, ar: "صَعْبَة", en: "Hard/difficult (f)" },
  { chapter: 9, ar: "صَعْب", en: "Hard/difficult (m)" },
  { chapter: 9, ar: "اللُّغَةُ الْإِنْجِلِيزِيَّة", en: "English language" },
  { chapter: 9, ar: "طَالِبَة", en: "Student" },
  { chapter: 9, ar: "كُوب", en: "Cup" },
  { chapter: 9, ar: "لِمَاذَا", en: "Why" },
  { chapter: 9, ar: "الْيَوْم", en: "Today" },
  { chapter: 9, ar: "عِنْد", en: "With (restrictions)" },
  { chapter: 9, ar: "مَكْتَبَة", en: "Library" },
  { chapter: 9, ar: "الَّذِي", en: "Who/which (m.s)" },
  { chapter: 9, ar: "صَغِيرَة", en: "Small" },
  { chapter: 9, ar: "مُسْتَوْصَف", en: "Clinic/small hospital" },
  { chapter: 9, ar: "مِرْوَحَة", en: "Fan" },
  { chapter: 9, ar: "جَدِيدَة", en: "New" },
  { chapter: 9, ar: "كَبِيرَة", en: "Big" },
  { chapter: 9, ar: "إِنْدُونِيسِيَا", en: "Indonesia" },
  { chapter: 9, ar: "ثَانَوِيَّة", en: "Secondary" },
  { chapter: 9, ar: "فَاكِهَة", en: "Fruit" },
  { chapter: 9, ar: "لَذِيذ", en: "Delicious" },
  { chapter: 9, ar: "عُصْفُور", en: "Sparrow" },
  { chapter: 9, ar: "طَائِر", en: "Bird" },
  { chapter: 9, ar: "الْعَرَبِيَّة", en: "Arabic" },
  { chapter: 9, ar: "لُغَة", en: "Language" },
  { chapter: 9, ar: "سَهْلَة", en: "Easy" },
  { chapter: 9, ar: "مُجْتَهِد", en: "Hardworking" },
  { chapter: 9, ar: "كَسْلَان", en: "Lazy" },
  { chapter: 9, ar: "سَهْل", en: "Easy" },
  { chapter: 9, ar: "الْقَاهِرَة", en: "Cairo" },
  { chapter: 9, ar: "مَدِينَة", en: "City" },
  { chapter: 9, ar: "جَوْعَان", en: "Hungry" },
  { chapter: 9, ar: "عَطْشَان", en: "Thirsty" },
  { chapter: 9, ar: "غَضْبَان", en: "Angry" },
  { chapter: 9, ar: "مَلْآن", en: "Full" },
  { chapter: 9, ar: "حَادّ", en: "Sharp" },

  // ---------------- Lesson 10 ----------------
  { chapter: 10, ar: "أُسَامَة", en: "Usaamah" },
  { chapter: 10, ar: "زَوْج", en: "Husband" },
  { chapter: 10, ar: "حَمْزَة", en: "Hamzah" },
  { chapter: 10, ar: "عِكْرِمَة", en: "Iqrimah" },
  { chapter: 10, ar: "أَخُوكَ", en: "Your (sing.m) brother" },
  { chapter: 10, ar: "لِي", en: "I have" },
  { chapter: 10, ar: "لَا مَا عِنْدِي", en: "No, I don’t have" },
  { chapter: 10, ar: "مَحْمُود", en: "Mahmood" },
  { chapter: 10, ar: "طِفْل", en: "Child" },
  { chapter: 10, ar: "لَهَا", en: "It/She has" },
  { chapter: 10, ar: "الرِّيَاض", en: "Riyadh" },
  { chapter: 10, ar: "الطَّائِف", en: "Taif (City)" },
  { chapter: 10, ar: "طَلْحَة", en: "Talha" },
  { chapter: 10, ar: "مُعَاوِيَة", en: "Mu’aawiyah" },
  { chapter: 10, ar: "أُخْت", en: "A sister" },
  { chapter: 10, ar: "اِسْم", en: "Name" },
  { chapter: 10, ar: "مَا لُغَتُكَ؟", en: "What is your (sing.m) language?" },
  { chapter: 10, ar: "اِسْمِي", en: "My name is" },
  { chapter: 10, ar: "مَا اسْمُهُ", en: "What is his name?" },
  { chapter: 10, ar: "الْأُرْدِيَّة", en: "Urdu" },
  { chapter: 10, ar: "مَع", en: "With (without restrictions)" },
  { chapter: 10, ar: "زَمِيل", en: "Colleague/classmate" },
  { chapter: 10, ar: "أَيْضًا", en: "Also" },
  { chapter: 10, ar: "الْيَابَانِيَّة", en: "Japanese (language)" },
  { chapter: 10, ar: "وَاحِد", en: "One" },
  { chapter: 10, ar: "الْكُوَيْت", en: "Kuwait" },
  { chapter: 10, ar: "أُمُّكَ", en: "Your (sing.m) mother" },
  { chapter: 10, ar: "ذَهَبْتُ", en: "I went" },
  { chapter: 10, ar: "أَبُوهُ", en: "His father" },
  { chapter: 10, ar: "أَعِنْدَكَ...؟", en: "Do you (sing.m) have…?" },

  // ---------------- Lesson 11 ----------------
  { chapter: 11, ar: "أَمَام", en: "In front" },
  { chapter: 11, ar: "فِيهَا", en: "In it (f)" },
  { chapter: 11, ar: "فِيهِ", en: "In it (m)" },
  { chapter: 11, ar: "تَحْت", en: "Under" },
  { chapter: 11, ar: "مَفْتُوحَة", en: "Open" },
  { chapter: 11, ar: "عِنْدِي", en: "I have" },
  { chapter: 11, ar: "خَرَجَتْ", en: "She left" },
  { chapter: 11, ar: "سُعَاد", en: "Su’aad" },
  { chapter: 11, ar: "أُحِبّ", en: "I love" },
  { chapter: 11, ar: "أَحَد", en: "One (someone)" },
  { chapter: 11, ar: "نَبِيّ", en: "Prophet" },
  { chapter: 11, ar: "تُحِبّ", en: "You love" },
  { chapter: 11, ar: "وَاحِد", en: "One" },
  { chapter: 11, ar: "سَعْد", en: "Sa’d" },

  // ---------------- Lesson 12 ----------------
  { chapter: 12, ar: "ذَهَبْتَ", en: "You went (sing.m)" },
  { chapter: 12, ar: "ذَهَبَتْ", en: "She went" },
  { chapter: 12, ar: "أُسْتَاذِي", en: "My teacher" },
  { chapter: 12, ar: "مَالَيْزِيَا", en: "Malaysia" },
  { chapter: 12, ar: "الَّتِي", en: "Who/which (sing.f)" },
  { chapter: 12, ar: "أَب", en: "Father" },
  { chapter: 12, ar: "آبَاء", en: "Fathers" },
  { chapter: 12, ar: "شَيْخ", en: "Scholar" },
  { chapter: 12, ar: "شُيُوخ", en: "Scholars" },
  { chapter: 12, ar: "ضَعِيف", en: "Weak" },
  { chapter: 12, ar: "ضُعَاف", en: "Weak (pl)" },
  { chapter: 12, ar: "عَمَّة", en: "Paternal aunt" },
  { chapter: 12, ar: "خَالَة", en: "Maternal aunt" },
  { chapter: 12, ar: "سَيِّد", en: "Sir" },
  { chapter: 12, ar: "سَيِّدَة", en: "Madam" },
  { chapter: 12, ar: "أُمّ", en: "Mother" },
  { chapter: 12, ar: "أُمَّهَات", en: "Mothers" },
  { chapter: 12, ar: "وَزِير", en: "Minister" },
  { chapter: 12, ar: "وُزَرَاء", en: "Ministers" },
  { chapter: 12, ar: "الْمَمْلَكَةُ الْعَرَبِيَّةُ السُّعُودِيَّة", en: "Kingdom of Saudi Arabia" },
  { chapter: 12, ar: "كَيْفَ حَالُكَ؟", en: "How are you? (sing.m)" },
  { chapter: 12, ar: "أَنَا بِخَيْر", en: "I am fine" },
  { chapter: 12, ar: "مُوَجِّه", en: "Director" },
  { chapter: 12, ar: "طَبِيبَة", en: "Doctor" },
  { chapter: 12, ar: "وِلَادَة", en: "Maternity" },
  { chapter: 12, ar: "فَتَاة", en: "Young woman" },
  { chapter: 12, ar: "سُعَاد", en: "Sa’ad" },
  { chapter: 12, ar: "خَرَجَتْ", en: "She left" },
  { chapter: 12, ar: "شَجَرَة", en: "Tree" },
  { chapter: 12, ar: "سُورِيَا", en: "Syria" },
  { chapter: 12, ar: "الْمَدْرَسَةُ الْمُتَوَسِّطَة", en: "Middle school" },
  { chapter: 12, ar: "مُفَتِّش", en: "Inspector" },
  { chapter: 12, ar: "أَنْتِ", en: "You (sing.f)" },
  { chapter: 12, ar: "بِلَال", en: "Bilal" },
  { chapter: 12, ar: "ذَهَبْتُ", en: "I went" },
  { chapter: 12, ar: "قَوِيّ", en: "Strong" },
  { chapter: 12, ar: "أَقْوِيَاء", en: "Strong (pl)" },
  { chapter: 12, ar: "بَعْد", en: "After" },
  { chapter: 12, ar: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللّٰهِ وَبَرَكَاتُهُ", en: "Peace be upon you and Allah’s mercy and blessings" },

  // ---------------- Lesson 13 ----------------
  { chapter: 13, ar: "فَقِير", en: "Poor" },
  { chapter: 13, ar: "فُقَرَاء", en: "Poor (pl)" },
  { chapter: 13, ar: "غَنِيّ", en: "Rich" },
  { chapter: 13, ar: "أَغْنِيَاء", en: "Rich (pl)" },
  { chapter: 13, ar: "صَدِيق", en: "Friend" },
  { chapter: 13, ar: "أَصْدِقَاء", en: "Friends" },
  { chapter: 13, ar: "طَبِيب", en: "Doctor" },
  { chapter: 13, ar: "أَطِبَّاء", en: "Doctors" },
  { chapter: 13, ar: "فَتًى", en: "Young man" },
  { chapter: 13, ar: "فِتْيَة", en: "Young men" },
  { chapter: 13, ar: "أَخ", en: "Brother" },
  { chapter: 13, ar: "إِخْوَة", en: "Brothers" },
  { chapter: 13, ar: "جُدُد", en: "New (pl.m/f)" },
  { chapter: 13, ar: "مُدَرِّس", en: "Teacher" },
  { chapter: 13, ar: "مُدَرِّسُون", en: "Teachers" },
  { chapter: 13, ar: "مُهَنْدِس", en: "Engineer" },
  { chapter: 13, ar: "مُهَنْدِسُون", en: "Engineers" },
  { chapter: 13, ar: "فَلَّاح", en: "Farmer" },
  { chapter: 13, ar: "فَلَّاحُون", en: "Farmers" },
  { chapter: 13, ar: "مُجْتَهِد", en: "Hardworking" },
  { chapter: 13, ar: "هَؤُلَاءِ", en: "These (pl.m/f)" },
  { chapter: 13, ar: "بَعْضُهُمْ", en: "Some of them (pl.m)" },
  { chapter: 13, ar: "طَالِب", en: "Student" },
  { chapter: 13, ar: "طُلَّاب", en: "Students" },
  { chapter: 13, ar: "تَاجِر", en: "Merchant" },
  { chapter: 13, ar: "تُجَّار", en: "Merchants" },
  { chapter: 13, ar: "حَاجّ", en: "Pilgrim" },
  { chapter: 13, ar: "حُجَّاج", en: "Pilgrims" },
  { chapter: 13, ar: "رَجُل", en: "Man" },
  { chapter: 13, ar: "رِجَال", en: "Men" },
  { chapter: 13, ar: "كَبِير", en: "Big" },
  { chapter: 13, ar: "كِبَار", en: "Big (pl.m/f)" },
  { chapter: 13, ar: "صَغِير", en: "Small" },
  { chapter: 13, ar: "صِغَار", en: "Small (pl.m/f)" },
  { chapter: 13, ar: "قَصِير", en: "Short" },
  { chapter: 13, ar: "قِصَار", en: "Short (pl.m/f)" },
  { chapter: 13, ar: "طَوِيل", en: "Tall" },
  { chapter: 13, ar: "طِوَال", en: "Tall (pl.m/f)" },
  { chapter: 13, ar: "وَلَد", en: "Boy" },
  { chapter: 13, ar: "أَوْلَاد", en: "Boys" },

  // ---------------- Lesson 14 ----------------
  { chapter: 14, ar: "أَنْتُمْ", en: "You (pl.m)" },
  { chapter: 14, ar: "كُمْ", en: "Your (pl.m) (attached pronoun)" },
  { chapter: 14, ar: "أَنَا", en: "I" },
  { chapter: 14, ar: "نَحْنُ", en: "We" },
  { chapter: 14, ar: "بَيْتُنَا", en: "Our house" },
  { chapter: 14, ar: "إِخْوَان", en: "Brothers" },
  { chapter: 14, ar: "اللّٰهُ رَبُّنَا", en: "Allah is our Lord" },
  { chapter: 14, ar: "الْإِسْلَامُ دِينُنَا", en: "Islam is our religion" },
  { chapter: 14, ar: "مُحَمَّدٌ نَبِيُّنَا", en: "Muhammad is our prophet" },
  { chapter: 14, ar: "ذَهَبْتُمْ", en: "You went (pl.m)" },
  { chapter: 14, ar: "ذَهَبَ", en: "He went" },
  { chapter: 14, ar: "بَلَد", en: "Country" },
  { chapter: 14, ar: "بِلَاد", en: "Countries" },
  { chapter: 14, ar: "وَلِيم", en: "William" },
  { chapter: 14, ar: "هِتْلَر", en: "Hitler" },
  { chapter: 14, ar: "لَنْدَن", en: "London" },
  { chapter: 14, ar: "آدَم", en: "Adam" },
  { chapter: 14, ar: "الْيُونَان", en: "Greece" },
  { chapter: 14, ar: "طِفْلَة", en: "Child" },
  { chapter: 14, ar: "مَطَار", en: "Airport" },
  { chapter: 14, ar: "دُكْتُور", en: "Doctor/professor" },
  { chapter: 14, ar: "الْيَوْم", en: "The day" },
  { chapter: 14, ar: "لِزِيَارَة", en: "To visit" },
  { chapter: 14, ar: "إِدْوَارْد", en: "Edward" },
  { chapter: 14, ar: "بَارِيس", en: "Paris" },
  { chapter: 14, ar: "بَاكِسْتَان", en: "Pakistan" },
  { chapter: 14, ar: "إِسْطَنْبُول", en: "Istanbul" },
  { chapter: 14, ar: "أَيُّوب", en: "Ayub" },
  { chapter: 14, ar: "سُلَيْمَان", en: "Sulaiman" },
  { chapter: 14, ar: "دَاوُد", en: "Dawud" },
  { chapter: 14, ar: "يُونُس", en: "Yunus" },
  { chapter: 14, ar: "إِدْرِيس", en: "Idrees" },
  { chapter: 14, ar: "جِبْرَائِيل", en: "Jibraeel" },
  { chapter: 14, ar: "مِيكَائِيل", en: "Mikaeel" },
  { chapter: 14, ar: "فِرْعَوْن", en: "Pharaoh" },
  { chapter: 14, ar: "أَيّ", en: "Which?" },
  { chapter: 14, ar: "إِبْرَاهِيم", en: "Ibraheem" },
  { chapter: 14, ar: "إِسْحَاق", en: "Ishaaq" },
  { chapter: 14, ar: "إِسْمَاعِيل", en: "Ismaeel" },
  { chapter: 14, ar: "يَعْقُوب", en: "Yaqub" },

  // ---------------- Lesson 15 ----------------
  { chapter: 15, ar: "قَبْل", en: "Before" },
  { chapter: 15, ar: "بَعْد", en: "After" },
  { chapter: 15, ar: "كَيْف", en: "How" },
  { chapter: 15, ar: "مَتَى", en: "When" },
  { chapter: 15, ar: "أَذَان", en: "Adhan" },
  { chapter: 15, ar: "صَلَاة", en: "Prayer" },
  { chapter: 15, ar: "رَجَعَ", en: "He returned" },
  { chapter: 15, ar: "دَرْس", en: "Lesson" },
  { chapter: 15, ar: "أَنْتُنَّ", en: "You (pl.f)" },
  { chapter: 15, ar: "كُنَّ", en: "Your (attached pronoun, pl.f)" },
  { chapter: 15, ar: "ذَهَبَتْ", en: "She went" },
  { chapter: 15, ar: "ذَهَبْنَ", en: "They went (f.pl)" },
  { chapter: 15, ar: "اِخْتِبَار", en: "Examination" },
  { chapter: 15, ar: "الْقَاهِرَة", en: "Cairo" },
  { chapter: 15, ar: "أُسْبُوع", en: "Week" },

  // ---------------- Lesson 16 ----------------
  { chapter: 16, ar: "بَلْجِيكَا", en: "Belgium" },
  { chapter: 16, ar: "بُيُوت", en: "Houses" },
  { chapter: 16, ar: "دُرُوس", en: "Lessons" },
  { chapter: 16, ar: "أَبْوَاب", en: "Doors" },
  { chapter: 16, ar: "أَنْهَار", en: "Rivers" },
  { chapter: 16, ar: "كِلَاب", en: "Dogs" },
  { chapter: 16, ar: "بِحَار", en: "Sea (pl)" },
  { chapter: 16, ar: "بَحْر", en: "Sea" },
  { chapter: 16, ar: "دَرَّاجَات", en: "Bikes" },
  { chapter: 16, ar: "حَمِير", en: "Donkeys" },
  { chapter: 16, ar: "سُرُر", en: "Beds" },
  { chapter: 16, ar: "دَفَاتِر", en: "Notebooks" },
  { chapter: 16, ar: "مَكَاتِب", en: "Desks" },
  { chapter: 16, ar: "فُنْدُق", en: "Hotel" },
  { chapter: 16, ar: "فَنَادِق", en: "Hotels" },
  { chapter: 16, ar: "سَاعَات", en: "Watches" },
  { chapter: 16, ar: "سَيَّارَات", en: "Cars" },
  { chapter: 16, ar: "طَائِرَة", en: "Airplane" },
  { chapter: 16, ar: "طَائِرَات", en: "Airplanes" },

  // ---------------- Lesson 17 ----------------
  { chapter: 17, ar: "مَفْتُوحَة", en: "Open" },
  { chapter: 17, ar: "لُغَة", en: "Language" },
  { chapter: 17, ar: "لُغَات", en: "Languages" },
  { chapter: 17, ar: "كَثِيرَة", en: "Many" },
  { chapter: 17, ar: "مَكْتَبَة", en: "Library" },
  { chapter: 17, ar: "مَكْسُورَة", en: "Broken" },
  { chapter: 17, ar: "رَخِيصَة", en: "Cheap" },
  { chapter: 17, ar: "شَارِع", en: "Street" },
  { chapter: 17, ar: "مِنْدِيل", en: "Handkerchief" },
  { chapter: 17, ar: "مَنَادِيل", en: "Handkerchiefs" },
  { chapter: 17, ar: "شَرِكَة", en: "Firm/company" },
  { chapter: 17, ar: "شَرِكَات", en: "Firms/Companies" },
  { chapter: 17, ar: "قُمُصَان", en: "Shirts" },
  { chapter: 17, ar: "مُدِيرُ الشَّرِكَة", en: "Director of company" },

  // ---------------- Lesson 18 ----------------
  { chapter: 18, ar: "عِيدُ الْفِطْر", en: "Eid ul fitr" },
  { chapter: 18, ar: "عِيدُ الْأَضْحَى", en: "Eid ul adha" },
  { chapter: 18, ar: "هَذَان", en: "This is (dual, m)" },
  { chapter: 18, ar: "هَاتَان", en: "This is (dual, f)" },
  { chapter: 18, ar: "هُمَا", en: "They (dual,m/f)" },
  { chapter: 18, ar: "كَم", en: "How many/much" },
  { chapter: 18, ar: "أَخَوَان", en: "2 brothers" },
  { chapter: 18, ar: "رِيَال", en: "Riyal" },
  { chapter: 18, ar: "مَتْجَر", en: "Business/shop" },
  { chapter: 18, ar: "رَكْعَة", en: "Rakah" },
  { chapter: 18, ar: "رَكَعَات", en: "Rakah (pl)" },
  { chapter: 18, ar: "عَجَلَة", en: "Wheel" },
  { chapter: 18, ar: "عِيد", en: "Festival/Celebration" },
  { chapter: 18, ar: "سَنَة", en: "Year" },
  { chapter: 18, ar: "نَافِذَة", en: "Window" },
  { chapter: 18, ar: "مِسْطَرَة", en: "Ruler" },
  { chapter: 18, ar: "حَيّ", en: "Area" },
  { chapter: 18, ar: "أَحْيَاء", en: "Areas" },
  { chapter: 18, ar: "عَجَلَات", en: "Wheels" },
  { chapter: 18, ar: "رِيَالَات", en: "Riyaals" },
  { chapter: 18, ar: "مَسَاطِر", en: "Rulers" },

  // ---------------- Lesson 19 ----------------
  { chapter: 19, ar: "رَاكِب", en: "Passenger" },
  { chapter: 19, ar: "رُكَّاب", en: "Passengers" },
  { chapter: 19, ar: "قُدَامَى", en: "Old (pl.m/f)" },
  { chapter: 19, ar: "جَيْب", en: "Pocket" },
  { chapter: 19, ar: "كُلّ", en: "All" },
  { chapter: 19, ar: "كُلُّهُمْ", en: "All of them (pl.m)" },
  { chapter: 19, ar: "كُلُّكُمْ", en: "All of you (pl.m)" },
  { chapter: 19, ar: "كُلُّنَا", en: "All of us" },
  { chapter: 19, ar: "مُخْتَلِف", en: "Different" },
  { chapter: 19, ar: "حَافِلَة", en: "Bus" },
  { chapter: 19, ar: "مِنْهُمْ", en: "From them" },
  { chapter: 19, ar: "أُورُوبَّا", en: "Europe" },
  { chapter: 19, ar: "يُوغُسْلَافِيَا", en: "Yugoslavia" },
  { chapter: 19, ar: "سُؤَال", en: "Question" },
  { chapter: 19, ar: "أَسْئِلَة", en: "Questions" },
  { chapter: 19, ar: "حَافِلَات", en: "Buses" },
  { chapter: 19, ar: "جُيُوب", en: "Pockets" },
  { chapter: 19, ar: "عَشَرَة", en: "Ten (f)" },
  { chapter: 19, ar: "ثَلَاثَة", en: "Three (f)" },
  { chapter: 19, ar: "أَرْبَعَة", en: "Four (f)" },
  { chapter: 19, ar: "وَاحِد", en: "One (m)" },
  { chapter: 19, ar: "سَبْعَة", en: "Seven (f)" },
  { chapter: 19, ar: "خَمْسَة", en: "Five (m)" },
  { chapter: 19, ar: "ثَمَانِيَة", en: "Eight (f)" },
  { chapter: 19, ar: "سِتَّة", en: "Six (f)" },
  { chapter: 19, ar: "تِسْعَة", en: "Nine (f)" },
  { chapter: 19, ar: "اِثْنَان", en: "Two (m)" },
  { chapter: 19, ar: "شُكْرًا", en: "Thanks" },
  { chapter: 19, ar: "أَيَّام", en: "Days" },
  { chapter: 19, ar: "ثَمَن", en: "Price" },
  { chapter: 19, ar: "نِصْف", en: "Half" },
  { chapter: 19, ar: "قِرْش", en: "1/10th of a riyaal" },
  { chapter: 19, ar: "قُرُوش", en: "1/10th of riyaals" },

  // ---------------- Lesson 20 ----------------
  { chapter: 20, ar: "ثَلَاثُ بَنَات", en: "Three daughters" },
  { chapter: 20, ar: "أَرْبَعُ أُخْوَات", en: "Four sisters" },
  { chapter: 20, ar: "خَمْسُ أُمَّهَات", en: "Five mothers" },
  { chapter: 20, ar: "سِتُّ نِسَاء", en: "Six women" },
  { chapter: 20, ar: "سَبْعُ طَالِبَات", en: "Seven students (f)" },
  { chapter: 20, ar: "ثَمَانِي غُرَف", en: "Eight rooms" },
  { chapter: 20, ar: "عَشَرَة", en: "Ten (f)" },
  { chapter: 20, ar: "اِثْنَتَان", en: "Two (f)" },
  { chapter: 20, ar: "وَاحِدَة", en: "One (f)" },
  { chapter: 20, ar: "دَجَاجَة", en: "Chicken" },
  { chapter: 20, ar: "دَجَاجَات", en: "Chickens" },
  { chapter: 20, ar: "كُلِّيَّات", en: "Faculties" },
  { chapter: 20, ar: "عَمَّات", en: "Paternal aunts" },
  { chapter: 20, ar: "جَامِعَات", en: "Universities" },
  { chapter: 20, ar: "غُرَف", en: "Rooms" },
  { chapter: 20, ar: "سَلْمَى", en: "Salma" },
  { chapter: 20, ar: "ثَلَاثَةُ أَبْنَاء", en: "Three sons" },
  { chapter: 20, ar: "أَرْبَعَةُ إِخْوَة", en: "Four brothers" },
  { chapter: 20, ar: "خَمْسَةُ آبَاء", en: "Five fathers" },
  { chapter: 20, ar: "سِتَّةُ رِجَال", en: "Six men" },
  { chapter: 20, ar: "سَبْعَةُ طُلَّاب", en: "Seven students (m)" },
  { chapter: 20, ar: "ثَمَانِيَةُ بُيُوت", en: "Eight houses" },
  { chapter: 20, ar: "عَشَر", en: "Ten (m)" },
  { chapter: 20, ar: "اِثْنَان", en: "Two (m)" },
  { chapter: 20, ar: "وَاحِد", en: "One (m)" },
  { chapter: 20, ar: "كَلِمَة", en: "Word" },
  { chapter: 20, ar: "كَلِمَات", en: "Words" },
  { chapter: 20, ar: "مَجَلَّة", en: "Magazine/Journal" },
  { chapter: 20, ar: "مَجَلَّات", en: "Magazines/Journals" },
  { chapter: 20, ar: "حَرْف", en: "Letter (alphabet)" },
  { chapter: 20, ar: "حُرُوف", en: "Letters (alphabet)" },

  // ---------------- Lesson 21 ----------------
  { chapter: 21, ar: "كَثِيرًا", en: "Very much/many" },
  { chapter: 21, ar: "أَم", en: "Or (used for questioning)" },
  { chapter: 21, ar: "مُغْلَقَة", en: "Closed" },
  { chapter: 21, ar: "إِفْرِيقِيَا", en: "Africa" },
  { chapter: 21, ar: "مَكَاتِب", en: "Desks" },
  { chapter: 21, ar: "كَرَاسِي", en: "Chairs" },
  { chapter: 21, ar: "قِبْلَة", en: "Direction of prayer" },
  { chapter: 21, ar: "ذَاك", en: "That" },
  { chapter: 21, ar: "الْيُونَان", en: "Greece" },
  { chapter: 21, ar: "لَوْن", en: "Colour" },
  { chapter: 21, ar: "أَلْوَان", en: "Colours" },
  { chapter: 21, ar: "نُحِبّ", en: "We love" },
  { chapter: 21, ar: "نُحِبُّهُ", en: "We love him" },
  { chapter: 21, ar: "آسِيَا", en: "Asia" },
  { chapter: 21, ar: "وَاسِع", en: "Spacious" },
  { chapter: 21, ar: "قَرِيبَة", en: "Near" },
  { chapter: 21, ar: "فَصْل", en: "Classroom" },
  { chapter: 21, ar: "فُصُول", en: "Classrooms" },
  { chapter: 21, ar: "نَافِذَتَان", en: "Two windows" },
  { chapter: 21, ar: "أَحْمَد", en: "Ahmad" },
  { chapter: 21, ar: "غَانَا", en: "Ghana" },
  { chapter: 21, ar: "نِيجِيرِيَا", en: "Nigeria" },
  { chapter: 21, ar: "بَيْرَم", en: "Bayrum" },
  { chapter: 21, ar: "أَبُو بَكْر", en: "Abu Bakr" },
  { chapter: 21, ar: "وَلَكِن", en: "But" },
  { chapter: 21, ar: "يُوسُف", en: "Yusuf" },
  { chapter: 21, ar: "صَالِح", en: "Righteous" },

  // ---------------- Lesson 22 ----------------
  { chapter: 22, ar: "فِنْجَان", en: "Tea cup" },
  { chapter: 22, ar: "فَنَاجِين", en: "Tea cups" },
  { chapter: 22, ar: "دَقِيقَة", en: "Minute" },
  { chapter: 22, ar: "دَقَائِق", en: "Minutes" },
  { chapter: 22, ar: "مِفْتَاح", en: "Key" },
  { chapter: 22, ar: "مَفَاتِيح", en: "Keys" },
  { chapter: 22, ar: "قَالَتْ", en: "She said" },
  { chapter: 22, ar: "أَحْمَر", en: "Red" },
  { chapter: 22, ar: "أَزْرَق", en: "Blue" },
  { chapter: 22, ar: "أَخْضَر", en: "Green" },
  { chapter: 22, ar: "أَسْوَد", en: "Black" },
  { chapter: 22, ar: "أَصْفَر", en: "Yellow" },
  { chapter: 22, ar: "أَبْيَض", en: "White" },
  { chapter: 22, ar: "قَالَ", en: "He said" },
  { chapter: 22, ar: "مَكَّة", en: "Makkah" },
  { chapter: 22, ar: "عُثْمَان", en: "Uthmaan" },
  { chapter: 22, ar: "طَالِبَان", en: "Two students" },
  { chapter: 22, ar: "كَثِيرَة", en: "Many" },
  { chapter: 22, ar: "قَلِيلَة", en: "Few" },
  { chapter: 22, ar: "عَفَّان", en: "Affaan" },
  { chapter: 22, ar: "سُفْيَان", en: "Sufyaan" },
  { chapter: 22, ar: "مَرْوَان", en: "Marwaan" },
  { chapter: 22, ar: "نُعْمَان", en: "Nu’maan" },
  { chapter: 22, ar: "شَبْعَان", en: "Full/satisfied" },
  { chapter: 22, ar: "أَنْوَر", en: "Anwar" },
  { chapter: 22, ar: "أَكْبَر", en: "Akbar" },
  { chapter: 22, ar: "مَسَاجِد", en: "Mosques" },
  { chapter: 22, ar: "مَدَارِس", en: "Schools" },
  { chapter: 22, ar: "بَغْدَاد", en: "Baghdad" },
  { chapter: 22, ar: "جِدَّة", en: "Jeddah" },

  // ---------------- Lesson 23 ----------------
  { chapter: 23, ar: "كَعْبَة", en: "Kabah" },
  { chapter: 23, ar: "لُوِيس", en: "Lewis" },
  { chapter: 23, ar: "وَاشِنْطُن", en: "Washington" },
  { chapter: 23, ar: "هَاتِ", en: "Bring (command)" }
];
