INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مَنْ هٰذَا؟", "Who is this?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "طَبِيبٌ", "Doctor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "وَلَدٌ", "Boy", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "طَالِبٌ", "Student", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "رَجُلٌ", "Man", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "تَاجِرٌ", "Merchant", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "كَلْبٌ", "Dog", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "قِطٌّ", "Cat", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "حِمَارٌ", "Donkey", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "حِصَانٌ", "Horse", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "وَ", "And", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "جَمَلٌ", "Camel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "دِيكٌ", "Rooster", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مُدَرِّسٌ", "Teacher", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مِنْدِيلٌ", "Handkerchief", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "نَجْمٌ", "Star", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "هٰذَا", "This (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "بَيْتٌ", "House", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مَسْجِدٌ", "Mosque", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "بَابٌ", "Door", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "كِتَابٌ", "Book", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "قَلَمٌ", "Pen", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مِفْتَاحٌ", "Key", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مَكْتَبٌ", "Desk", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "سَرِيرٌ", "Bed", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "كُرْسِيٌّ", "Chair", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مَا هٰذَا؟", "What is this?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "أَهٰذَا؟", "Is this?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "نَعَمْ", "Yes", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "قَمِيصٌ", "Shirt", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "لَا", "No", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (1, "مَنْ", "Who", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "مَا؟", "What?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "حَجَرٌ", "Stone", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "لَبَنٌ", "Milk", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "ذَٰلِكَ", "That", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "أَذَٰلِكَ؟", "Is that?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "إِمَامٌ", "Leader", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "سُكَّرٌ", "Sugar", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (2, "مَا ذَٰلِكَ؟", "What is that?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ثَقِيلٌ", "Heavy", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "قَمَرٌ", "Moon", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "خَفِيفٌ", "Light", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "نَظِيفٌ", "Clean", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "فَقِيرٌ", "Poor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "حُلْوٌ", "Sweet", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "مَرِيضٌ", "Sick", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "دَفْتَرٌ", "Notebook", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "دُكَّانٌ", "Shop", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "غَنِيٌّ", "Rich", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "أَبٌ", "Father", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "وَرَقٌ", "Paper", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "تُفَّاحٌ", "Apple", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "لَذِيذٌ", "Delicious", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "طَبِيبٌ", "Doctor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "طَوِيلٌ", "Tall", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "قَصِيرٌ", "Short", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "أَخٌ", "Brother", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "رَسُولٌ", "Messenger", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ال", "The", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "مَكْسُورٌ", "Broken", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "مَفْتُوحٌ", "Open", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "جَالِسٌ", "Sitting", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "وَاقِفٌ", "Standing", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "جَدِيدٌ", "New", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "قَدِيمٌ", "Old", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "مَاءٌ", "Water", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "بَارِدٌ", "Cold", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "قَرِيبٌ", "Near", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "بَعِيدٌ", "Far", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "حَارٌّ", "Hot", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "صَغِيرٌ", "Small", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "كَبِيرٌ", "Big", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "وَسِخٌ", "Dirty", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "جَمِيلٌ", "Beautiful", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "خُبْزٌ", "Bread", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "عَيْنٌ", "Eye", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "وَجْهٌ", "Face", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "صَدِيقٌ", "Friend", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "قُرْآنٌ", "Quraan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "صَلَاةٌ", "Prayer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "كَعْبَةٌ", "Kabah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "رَأْسٌ", "Head", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "إِصْبَعٌ", "Finger", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "صَابُونٌ", "Soap", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ظُفْرٌ", "Nail", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "فَجْرٌ", "Dawn", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ظُهْرٌ", "Midday", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "عَصْرٌ", "Afternoon/time", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "مَغْرِبٌ", "Sunset", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "عِشَاءٌ", "Evening", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "جَنَّةٌ", "Garden/paradise", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "غَدَاءٌ", "Lunch/dinner", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "فَمٌ", "Mouth", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "هَوَاءٌ", "Air", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "يَدٌ", "Hand", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ثَوْبٌ", "Garment", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ذَهَبٌ", "Gold", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "زَهْرَةٌ", "A flower", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "سَمَكٌ", "A fish", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "شَمْسٌ", "A sun", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "صَدْرٌ", "Chest", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ضَيْفٌ", "Guest", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "ظَهْرٌ", "Back", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (3, "لَحْمٌ", "Meat", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مِرْحَاضٌ", "Toilet", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "سَمَاءٌ", "Sky", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "خَالِدٌ", "Khaalid", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "حَامِدٌ", "Haamid", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "فَاطِمَةُ", "Fatimah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مَرْيَمُ", "Maryam", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "عَائِشَةُ", "Aa’isha", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "خَدِيجَةُ", "Khadeejah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "صَفِيَّةُ", "Safiyyah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "عَمَّارٌ", "Ammaar", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "سَعِيدٌ", "Sa’eed", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "عَلِيٌّ", "Ali", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "رُقَيَّةُ", "Ruqayyah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مِنْ", "From", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "إِلَى", "To", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "أَنْتَ", "You (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "خَرَجَ", "He left", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "ذَهَبَ", "He went", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مُدِيرٌ", "Headmaster", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "فِي", "In", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "عَلَى", "On", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "أَيْنَ", "Where", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مُحَمَّدٌ", "Muhammad", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "هُوَ", "He", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "غُرْفَةٌ", "A room", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "يَاسِرُ", "Yaasir", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "حَمَّامٌ", "Bathroom", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "آمِنَةُ", "Aaminah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مَطْبَخٌ", "Kitchen", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "هِيَ", "She", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "سَاعَةٌ", "Watch", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "مَدْرَسَةٌ", "School", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "جَامِعَةٌ", "University", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "زَيْنَبُ", "Zainab", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "فَصْلٌ", "Classroom", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "أَنَا", "I", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "الْيَابَانُ", "Japan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "الصِّينُ", "China", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "الْهِنْدُ", "India", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "سُوقٌ", "Market", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (4, "الْفِلِبِّينُ", "Philippines", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "فَيْصَل", "Faisal", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "مَسْعُود", "Masood", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "وَزِير", "Minister", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "أُسْتَاذ", "Teacher/Professor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "سَيَّارَة", "Car", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "اِبْن", "Son", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "اللّٰه", "Allah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "اِسْم", "Name", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "الْعِرَاق", "Iraq", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "مُنَوَّرَة", "Illuminated", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "يَا", "O..", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "هُنَاك", "There", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "هُنَا", "Here", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "حَقِيبَة", "Bag", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "تَحْت", "Under/beneath", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "بِنْت", "Girl/daughter", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "عَمّ", "Paternal uncle", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "مُغْلَق", "Closed", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "خَال", "Maternal uncle", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (5, "شَارِع", "Street", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "أُذُن", "Ear", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "أَنْف", "Nose", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "مُسْلِم", "Muslim", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "شَاي", "Tea", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "سَرِيع", "Fast", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "نَافِذَة", "Window", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "قَهْوَة", "Coffee", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "ثَلَّاجَة", "Fridge", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "أُمّ", "Mother", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "فَلَّاح", "Farmer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "رِجْل", "Leg/foot", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "بَقَرَة", "Cow", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "قَدْر", "Cooking pot", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "مَشْرِق", "East", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "مَغْرِب", "West", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "هٰذِهِ", "This is (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "أُخْت", "Sister", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "أَيْضًا", "Also", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "لِمَنْ", "Whose", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "مِكْوَاة", "Iron", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "جَدِيدَة", "New", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "دَرَّاجَة", "Bicycle", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "طَبِيبَة", "Doctor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "أَنَس", "Anas", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "جِدًّا", "Very", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "جَمِيلَة", "Beautiful", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "مِلْعَقَة", "Spoon", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "عَيْن", "Eye", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (6, "الْحَمْدُ لِلّٰهِ", "Praise belongs to Allah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "تِلْكَ", "That is", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "مُمَرِّضَة", "Nurse", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "طَوِيلَة", "Tall", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "دَجَاجَة", "Chicken", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "نَاقَة", "She camel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "حَدِيقَة", "Garden", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "قَصِيرَة", "Short", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "بَطَّة", "Duck", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "بَيْضَة", "Egg", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "مُؤَذِّن", "Caller to prayer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (7, "مُدَرِّسَة", "Teacher", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "خَلْف", "Behind", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "أَمَام", "In front of", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "أَمْرِيكَا", "America", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "سِكِّين", "Knife", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "إِنْكِلْتَرَا", "England", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "مُسْتَشْفَى", "Hospital", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "سُوَيْسَرَا", "Switzerland", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "أَلْمَانِيَا", "Germany", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "فَرَنْسَا", "France", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "الْآنَ", "Now/just now", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "عَبْدُ اللّٰهِ", "Abdullah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "عِيسَى", "Eesa", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "مُوسَى", "Musa", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "سَبُّورَة", "White/black board", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (8, "مِحْرَاب", "Niche", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مَشْهُور", "Famous", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "صَعْبَة", "Hard/difficult (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "صَعْب", "Hard/difficult (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "اللُّغَةُ الْإِنْجِلِيزِيَّة", "english, starred language", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "طَالِبَة", "Student", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "كُوب", "Cup", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "لِمَاذَا", "Why", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "الْيَوْم", "Today", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "عِنْد", "With (restrictions)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مَكْتَبَة", "Library", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "الَّذِي", "Who/which (m.s)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "صَغِيرَة", "Small", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مُسْتَوْصَف", "Clinic/small hospital", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مِرْوَحَة", "Fan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "جَدِيدَة", "New", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "كَبِيرَة", "Big", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "إِنْدُونِيسِيَا", "Indonesia", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "ثَانَوِيَّة", "Secondary", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "فَاكِهَة", "Fruit", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "لَذِيذ", "Delicious", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "عُصْفُور", "Sparrow", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "طَائِر", "Bird", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "الْعَرَبِيَّة", "Arabic", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "لُغَة", "Language", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "سَهْلَة", "Easy", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مُجْتَهِد", "Hardworking", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "كَسْلَان", "Lazy", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "سَهْل", "Easy", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "الْقَاهِرَة", "Cairo", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مَدِينَة", "City", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "جَوْعَان", "Hungry", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "عَطْشَان", "Thirsty", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "غَضْبَان", "Angry", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "مَلْآن", "Full", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (9, "حَادّ", "Sharp", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أُسَامَة", "Usaamah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "زَوْج", "Husband", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "حَمْزَة", "Hamzah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "عِكْرِمَة", "Iqrimah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أَخُوكَ", "Your (sing.m) brother", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "لِي", "I have", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "لَا مَا عِنْدِي", "No, I don’t have", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "مَحْمُود", "Mahmood", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "طِفْل", "Child", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "لَهَا", "It/She has", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "الرِّيَاض", "Riyadh", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "الطَّائِف", "Taif (City)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "طَلْحَة", "Talha", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "مُعَاوِيَة", "Mu’aawiyah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أُخْت", "A sister", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "اِسْم", "Name", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "مَا لُغَتُكَ؟", "What is your (sing.m) language?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "اِسْمِي", "My name is", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "مَا اسْمُهُ", "What is his name?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "الْأُرْدِيَّة", "Urdu", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "مَع", "With (without restrictions)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "زَمِيل", "Colleague/classmate", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أَيْضًا", "Also", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "الْيَابَانِيَّة", "Japanese (language)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "وَاحِد", "One", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "الْكُوَيْت", "Kuwait", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أُمُّكَ", "Your (sing.m) mother", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "ذَهَبْتُ", "I went", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أَبُوهُ", "His father", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (10, "أَعِنْدَكَ...؟", "Do you (sing.m) have…?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "أَمَام", "In front", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "فِيهَا", "In it (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "فِيهِ", "In it (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "تَحْت", "Under", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "مَفْتُوحَة", "Open", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "عِنْدِي", "I have", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "خَرَجَتْ", "She left", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "سُعَاد", "Su’aad", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "أُحِبّ", "I love", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "أَحَد", "One (someone)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "نَبِيّ", "Prophet", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "تُحِبّ", "You love", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "وَاحِد", "One", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (11, "سَعْد", "Sa’d", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "ذَهَبْتَ", "You went (sing.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "ذَهَبَتْ", "She went", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أُسْتَاذِي", "My teacher", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "مَالَيْزِيَا", "Malaysia", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "الَّتِي", "Who/which (sing.f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أَب", "Father", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "آبَاء", "Fathers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "شَيْخ", "Scholar", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "شُيُوخ", "Scholars", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "ضَعِيف", "Weak", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "ضُعَاف", "Weak (pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "عَمَّة", "Paternal aunt", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "خَالَة", "Maternal aunt", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "سَيِّد", "Sir", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "سَيِّدَة", "Madam", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أُمّ", "Mother", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أُمَّهَات", "Mothers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "وَزِير", "Minister", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "وُزَرَاء", "Ministers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "الْمَمْلَكَةُ الْعَرَبِيَّةُ السُّعُودِيَّة", "Kingdom of Saudi Arabia", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "كَيْفَ حَالُكَ؟", "How are you? (sing.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أَنَا بِخَيْر", "I am fine", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "مُوَجِّه", "Director", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "طَبِيبَة", "Doctor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "وِلَادَة", "Maternity", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "فَتَاة", "Young woman", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "سُعَاد", "Sa’ad", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "خَرَجَتْ", "She left", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "شَجَرَة", "Tree", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "سُورِيَا", "Syria", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "الْمَدْرَسَةُ الْمُتَوَسِّطَة", "Middle school", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "مُفَتِّش", "Inspector", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أَنْتِ", "You (sing.f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "بِلَال", "Bilal", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "ذَهَبْتُ", "I went", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "قَوِيّ", "Strong", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "أَقْوِيَاء", "Strong (pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "بَعْد", "After", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (12, "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللّٰهِ وَبَرَكَاتُهُ", "Peace be upon you and Allah’s mercy and blessings", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "فَقِير", "Poor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "فُقَرَاء", "Poor (pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "غَنِيّ", "Rich", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "أَغْنِيَاء", "Rich (pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "صَدِيق", "Friend", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "أَصْدِقَاء", "Friends", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "طَبِيب", "Doctor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "أَطِبَّاء", "Doctors", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "فَتًى", "Young man", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "فِتْيَة", "Young men", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "أَخ", "Brother", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "إِخْوَة", "Brothers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "جُدُد", "New (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "مُدَرِّس", "Teacher", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "مُدَرِّسُون", "Teachers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "مُهَنْدِس", "Engineer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "مُهَنْدِسُون", "Engineers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "فَلَّاح", "Farmer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "فَلَّاحُون", "Farmers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "مُجْتَهِد", "Hardworking", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "هَؤُلَاءِ", "These (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "بَعْضُهُمْ", "Some of them (pl.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "طَالِب", "Student", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "طُلَّاب", "Students", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "تَاجِر", "Merchant", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "تُجَّار", "Merchants", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "حَاجّ", "Pilgrim", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "حُجَّاج", "Pilgrims", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "رَجُل", "Man", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "رِجَال", "Men", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "كَبِير", "Big", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "كِبَار", "Big (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "صَغِير", "Small", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "صِغَار", "Small (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "قَصِير", "Short", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "قِصَار", "Short (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "طَوِيل", "Tall", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "طِوَال", "Tall (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "وَلَد", "Boy", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (13, "أَوْلَاد", "Boys", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "أَنْتُمْ", "You (pl.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "كُمْ", "Your (pl.m) (attached pronoun)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "أَنَا", "I", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "نَحْنُ", "We", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "بَيْتُنَا", "Our house", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِخْوَان", "Brothers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "اللّٰهُ رَبُّنَا", "Allah is our Lord", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "الْإِسْلَامُ دِينُنَا", "Islam is our religion", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "مُحَمَّدٌ نَبِيُّنَا", "Muhammad is our prophet", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "ذَهَبْتُمْ", "You went (pl.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "ذَهَبَ", "He went", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "بَلَد", "Country", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "بِلَاد", "Countries", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "وَلِيم", "William", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "هِتْلَر", "Hitler", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "لَنْدَن", "London", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "آدَم", "Adam", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "الْيُونَان", "Greece", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "طِفْلَة", "Child", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "مَطَار", "Airport", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "دُكْتُور", "Doctor/professor", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "الْيَوْم", "The day", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "لِزِيَارَة", "To visit", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِدْوَارْد", "Edward", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "بَارِيس", "Paris", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "بَاكِسْتَان", "Pakistan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِسْطَنْبُول", "Istanbul", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "أَيُّوب", "Ayub", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "سُلَيْمَان", "Sulaiman", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "دَاوُد", "Dawud", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "يُونُس", "Yunus", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِدْرِيس", "Idrees", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "جِبْرَائِيل", "Jibraeel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "مِيكَائِيل", "Mikaeel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "فِرْعَوْن", "Pharaoh", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "أَيّ", "Which?", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِبْرَاهِيم", "Ibraheem", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِسْحَاق", "Ishaaq", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "إِسْمَاعِيل", "Ismaeel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (14, "يَعْقُوب", "Yaqub", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "قَبْل", "Before", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "بَعْد", "After", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "كَيْف", "How", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "مَتَى", "When", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "أَذَان", "Adhan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "صَلَاة", "Prayer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "رَجَعَ", "He returned", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "دَرْس", "Lesson", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "أَنْتُنَّ", "You (pl.f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "كُنَّ", "Your (attached pronoun, pl.f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "ذَهَبَتْ", "She went", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "ذَهَبْنَ", "They went (f.pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "اِخْتِبَار", "Examination", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "الْقَاهِرَة", "Cairo", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (15, "أُسْبُوع", "Week", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "بَلْجِيكَا", "Belgium", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "بُيُوت", "Houses", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "دُرُوس", "Lessons", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "أَبْوَاب", "Doors", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "أَنْهَار", "Rivers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "كِلَاب", "Dogs", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "بِحَار", "Sea (pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "بَحْر", "Sea", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "دَرَّاجَات", "Bikes", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "حَمِير", "Donkeys", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "سُرُر", "Beds", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "دَفَاتِر", "Notebooks", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "مَكَاتِب", "Desks", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "فُنْدُق", "Hotel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "فَنَادِق", "Hotels", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "سَاعَات", "Watches", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "سَيَّارَات", "Cars", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "طَائِرَة", "Airplane", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (16, "طَائِرَات", "Airplanes", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "مَفْتُوحَة", "Open", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "لُغَة", "Language", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "لُغَات", "Languages", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "كَثِيرَة", "Many", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "مَكْتَبَة", "Library", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "مَكْسُورَة", "Broken", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "رَخِيصَة", "Cheap", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "شَارِع", "Street", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "مِنْدِيل", "Handkerchief", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "مَنَادِيل", "Handkerchiefs", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "شَرِكَة", "Firm/company", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "شَرِكَات", "Firms/Companies", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "قُمُصَان", "Shirts", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (17, "مُدِيرُ الشَّرِكَة", "Director of company", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "عِيدُ الْفِطْر", "Eid ul fitr", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "عِيدُ الْأَضْحَى", "Eid ul adha", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "هَذَان", "This is (dual, m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "هَاتَان", "This is (dual, f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "هُمَا", "They (dual,m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "كَم", "How many/much", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "أَخَوَان", "2 brothers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "رِيَال", "Riyal", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "مَتْجَر", "Business/shop", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "رَكْعَة", "Rakah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "رَكَعَات", "Rakah (pl)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "عَجَلَة", "Wheel", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "عِيد", "Festival/Celebration", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "سَنَة", "Year", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "نَافِذَة", "Window", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "مِسْطَرَة", "Ruler", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "حَيّ", "Area", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "أَحْيَاء", "Areas", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "عَجَلَات", "Wheels", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "رِيَالَات", "Riyaals", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (18, "مَسَاطِر", "Rulers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "رَاكِب", "Passenger", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "رُكَّاب", "Passengers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "قُدَامَى", "Old (pl.m/f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "جَيْب", "Pocket", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "كُلّ", "All", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "كُلُّهُمْ", "All of them (pl.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "كُلُّكُمْ", "All of you (pl.m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "كُلُّنَا", "All of us", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "مُخْتَلِف", "Different", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "حَافِلَة", "Bus", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "مِنْهُمْ", "From them", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "أُورُوبَّا", "Europe", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "يُوغُسْلَافِيَا", "Yugoslavia", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "سُؤَال", "Question", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "أَسْئِلَة", "Questions", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "حَافِلَات", "Buses", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "جُيُوب", "Pockets", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "عَشَرَة", "Ten (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "ثَلَاثَة", "Three (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "أَرْبَعَة", "Four (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "وَاحِد", "One (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "سَبْعَة", "Seven (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "خَمْسَة", "Five (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "ثَمَانِيَة", "Eight (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "سِتَّة", "Six (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "تِسْعَة", "Nine (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "اِثْنَان", "Two (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "شُكْرًا", "Thanks", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "أَيَّام", "Days", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "ثَمَن", "Price", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "نِصْف", "Half", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "قِرْش", "1/10th of a riyaal", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (19, "قُرُوش", "1/10th of riyaals", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "ثَلَاثُ بَنَات", "Three daughters", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "أَرْبَعُ أُخْوَات", "Four sisters", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "خَمْسُ أُمَّهَات", "Five mothers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "سِتُّ نِسَاء", "Six women", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "سَبْعُ طَالِبَات", "Seven students (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "ثَمَانِي غُرَف", "Eight rooms", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "عَشَرَة", "Ten (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "اِثْنَتَان", "Two (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "وَاحِدَة", "One (f)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "دَجَاجَة", "Chicken", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "دَجَاجَات", "Chickens", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "كُلِّيَّات", "Faculties", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "عَمَّات", "Paternal aunts", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "جَامِعَات", "Universities", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "غُرَف", "Rooms", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "سَلْمَى", "Salma", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "ثَلَاثَةُ أَبْنَاء", "Three sons", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "أَرْبَعَةُ إِخْوَة", "Four brothers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "خَمْسَةُ آبَاء", "Five fathers", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "سِتَّةُ رِجَال", "Six men", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "سَبْعَةُ طُلَّاب", "Seven students (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "ثَمَانِيَةُ بُيُوت", "Eight houses", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "عَشَر", "Ten (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "اِثْنَان", "Two (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "وَاحِد", "One (m)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "كَلِمَة", "Word", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "كَلِمَات", "Words", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "مَجَلَّة", "Magazine/Journal", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "مَجَلَّات", "Magazines/Journals", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "حَرْف", "Letter (alphabet)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (20, "حُرُوف", "Letters (alphabet)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "كَثِيرًا", "Very much/many", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "أَم", "Or (used for questioning)", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "مُغْلَقَة", "Closed", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "إِفْرِيقِيَا", "Africa", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "مَكَاتِب", "Desks", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "كَرَاسِي", "Chairs", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "قِبْلَة", "Direction of prayer", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "ذَاك", "That", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "الْيُونَان", "Greece", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "لَوْن", "Colour", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "أَلْوَان", "Colours", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "نُحِبّ", "We love", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "نُحِبُّهُ", "We love him", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "آسِيَا", "Asia", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "وَاسِع", "Spacious", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "قَرِيبَة", "Near", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "فَصْل", "Classroom", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "فُصُول", "Classrooms", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "نَافِذَتَان", "Two windows", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "أَحْمَد", "Ahmad", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "غَانَا", "Ghana", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "نِيجِيرِيَا", "Nigeria", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "بَيْرَم", "Bayrum", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "أَبُو بَكْر", "Abu Bakr", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "وَلَكِن", "But", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "يُوسُف", "Yusuf", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (21, "صَالِح", "Righteous", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "فِنْجَان", "Tea cup", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "فَنَاجِين", "Tea cups", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "دَقِيقَة", "Minute", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "دَقَائِق", "Minutes", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "مِفْتَاح", "Key", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "مَفَاتِيح", "Keys", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "قَالَتْ", "She said", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَحْمَر", "Red", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَزْرَق", "Blue", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَخْضَر", "Green", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَسْوَد", "Black", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَصْفَر", "Yellow", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَبْيَض", "White", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "قَالَ", "He said", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "مَكَّة", "Makkah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "عُثْمَان", "Uthmaan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "طَالِبَان", "Two students", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "كَثِيرَة", "Many", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "قَلِيلَة", "Few", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "عَفَّان", "Affaan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "سُفْيَان", "Sufyaan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "مَرْوَان", "Marwaan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "نُعْمَان", "Nu’maan", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "شَبْعَان", "Full/satisfied", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَنْوَر", "Anwar", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "أَكْبَر", "Akbar", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "مَسَاجِد", "Mosques", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "مَدَارِس", "Schools", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "بَغْدَاد", "Baghdad", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (22, "جِدَّة", "Jeddah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (23, "كَعْبَة", "Kabah", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (23, "لُوِيس", "Lewis", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (23, "وَاشِنْطُن", "Washington", 0);
INSERT INTO vocab (chapter, arabic, english, starred) VALUES (23, "هَاتِ", "Bring (command)", 0);
